// The outlets the site reads: their own RSS / Atom feeds, in Russian or English only
// (countries are recognised by Russian and English words). `home` marks an outlet that writes
// mostly about one country: there one mention of that country in the summary is enough.
// 300 outlets (100 in Russian, 200 in English); every feed here passed check-feeds.mjs in October 2026
// (answers, has fresh items, right language). Feeds closed to robots (HTTP 403) are not added.
// A new outlet also goes into the Supabase table `outlets` (ratings page).
export const SOURCES = [
  // ---------- Russian-language ----------
  // Russia
  { name: "ТАСС", url: "https://tass.ru/rss/v2.xml", lang: "Russian" },
  { name: "РИА Новости", url: "https://ria.ru/export/rss2/archive/index.xml", lang: "Russian" },
  { name: "Интерфакс", url: "https://www.interfax.ru/rss.asp", lang: "Russian" },
  { name: "Коммерсантъ", url: "https://www.kommersant.ru/RSS/news.xml", lang: "Russian" },
  { name: "РБК", url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss", lang: "Russian" },
  { name: "Ведомости", url: "https://www.vedomosti.ru/rss/news", lang: "Russian" },
  { name: "Лента.ру", url: "https://lenta.ru/rss/news", lang: "Russian" },
  { name: "Газета.ру", url: "https://www.gazeta.ru/export/rss/first.xml", lang: "Russian" },
  { name: "Взгляд", url: "https://vz.ru/rss.xml", lang: "Russian" },
  { name: "Российская газета", url: "https://rg.ru/xml/index.xml", lang: "Russian" },
  { name: "Аргументы и факты", url: "https://aif.ru/rss/news.php", lang: "Russian" },
  { name: "Комсомольская правда", url: "https://www.kp.ru/rss/allsections.xml", lang: "Russian" },
  { name: "Московский комсомолец", url: "https://www.mk.ru/rss/index.xml", lang: "Russian" },
  { name: "RT на русском", url: "https://russian.rt.com/rss", lang: "Russian" },
  { name: "Life.ru", url: "https://life.ru/xml/feed.xml", lang: "Russian" },
  { name: "Meduza", url: "https://meduza.io/rss/all", lang: "Russian" },
  { name: "The Insider", url: "https://theins.ru/feed", lang: "Russian" },
  { name: "Регнум", url: "https://regnum.ru/rss", lang: "Russian" },
  { name: "ПРАЙМ", url: "https://1prime.ru/export/rss2/index.xml", lang: "Russian" },
  { name: "Профиль", url: "https://profile.ru/feed/", lang: "Russian" },
  { name: "Независимая газета", url: "https://www.ng.ru/rss/", lang: "Russian" },
  { name: "Парламентская газета", url: "https://www.pnp.ru/rss/index.xml", lang: "Russian" },
  { name: "Звезда", url: "https://tvzvezda.ru/export/rss.xml", lang: "Russian" },
  { name: "EADaily", url: "https://eadaily.com/ru/rss/index.xml", lang: "Russian" },
  { name: "Москва 24", url: "https://www.m24.ru/rss.xml", lang: "Russian" },
  { name: "Ura.ru", url: "https://ura.news/rss", lang: "Russian" },
  { name: "Финмаркет", url: "https://www.finmarket.ru/rss/mainnews.asp", lang: "Russian" },
  { name: "Версия", url: "https://versia.ru/rss/index.xml", lang: "Russian" },
  { name: "Политнавигатор", url: "https://www.politnavigator.net/feed", lang: "Russian" },
  { name: "Деловой Петербург", url: "https://www.dp.ru/exportnews.xml", lang: "Russian" },
  { name: "Финам", url: "https://www.finam.ru/analysis/conews/rsspoint/", lang: "Russian" },
  { name: "Новая газета Европа", url: "https://novayagazeta.eu/feed/rss", lang: "Russian" },
  { name: "Дождь", url: "https://tvrain.tv/export/rss/all.xml", lang: "Russian" },
  { name: "Медиазона", url: "https://zona.media/rss", lang: "Russian" },
  // International services in Russian
  { name: "BBC Русская служба", url: "https://feeds.bbci.co.uk/russian/rss.xml", lang: "Russian" },
  { name: "DW на русском", url: "https://rss.dw.com/rdf/rss-ru-all", lang: "Russian" },
  { name: "Euronews на русском", url: "https://ru.euronews.com/rss", lang: "Russian" },
  { name: "RFI на русском", url: "https://www.rfi.fr/ru/rss", lang: "Russian" },
  { name: "Anadolu на русском", url: "https://www.aa.com.tr/ru/rss/default?cat=guncel", lang: "Russian", home: "TR" },
  // Ukraine
  { name: "УНИАН", url: "https://rss.unian.net/site/news_rus.rss", lang: "Russian", home: "UA" },
  { name: "Украинская правда", url: "https://www.pravda.com.ua/rus/rss/view_news/", lang: "Russian", home: "UA" },
  { name: "Цензор.нет", url: "https://censor.net/includes/news_ru.xml", lang: "Russian", home: "UA" },
  { name: "РБК-Украина", url: "https://www.rbc.ua/static/rss/all.rus.rss.xml", lang: "Russian", home: "UA" },
  { name: "Зеркало недели", url: "https://zn.ua/rus/rss/full.rss", lang: "Russian", home: "UA" },
  { name: "Новое время", url: "https://nv.ua/rss/all.xml", lang: "Russian", home: "UA" },
  { name: "Обозреватель", url: "https://www.obozrevatel.com/rss.xml", lang: "Russian", home: "UA" },
  { name: "Фокус", url: "https://focus.ua/modules/rss.php", lang: "Russian", home: "UA" },
  { name: "Гордон", url: "https://gordonua.com/xml/rss_category/top.html", lang: "Russian", home: "UA" },
  { name: "Интерфакс-Украина", url: "https://interfax.com.ua/news/last.rss", lang: "Russian", home: "UA" },
  // Belarus
  { name: "БелТА", url: "https://www.belta.by/rss", lang: "Russian", home: "BY" },
  { name: "Sputnik Беларусь", url: "https://sputnik.by/export/rss2/archive/index.xml", lang: "Russian", home: "BY" },
  { name: "Хартия'97", url: "https://charter97.org/rss.php", lang: "Russian", home: "BY" },
  { name: "Минск-Новости", url: "https://minsknews.by/feed/", lang: "Russian", home: "BY" },
  { name: "Onliner", url: "https://www.onliner.by/feed", lang: "Russian", home: "BY" },
  // Kazakhstan
  { name: "Tengrinews", url: "https://tengrinews.kz/news.rss", lang: "Russian", home: "KZ" },
  { name: "Курсив", url: "https://kz.kursiv.media/feed/", lang: "Russian", home: "KZ" },
  { name: "Sputnik Казахстан", url: "https://ru.sputnik.kz/export/rss2/archive/index.xml", lang: "Russian", home: "KZ" },
  { name: "Nur.kz", url: "https://www.nur.kz/rss/all.rss", lang: "Russian", home: "KZ" },
  // Israel, Baltics, Moldova, Central Asia, Caucasus
  { name: "NEWSru.co.il", url: "https://www.newsru.co.il/il/www/rss/rss.xml", lang: "Russian", home: "IL" },
  { name: "LSM на русском", url: "https://rus.lsm.lv/rss/", lang: "Russian" },
  { name: "Postimees на русском", url: "https://rus.postimees.ee/rss", lang: "Russian" },
  { name: "Газета.uz", url: "https://www.gazeta.uz/ru/rss/", lang: "Russian" },
  { name: "Podrobno.uz", url: "https://podrobno.uz/rss/", lang: "Russian" },
  { name: "Kaktus.media", url: "https://kaktus.media/?rss", lang: "Russian" },
  { name: "News.am", url: "https://news.am/rus/rss/", lang: "Russian" },
  { name: "JAMnews", url: "https://jam-news.net/ru/feed/", lang: "Russian" },
  { name: "Sputnik Армения", url: "https://am.sputniknews.ru/export/rss2/archive/index.xml", lang: "Russian" },
  { name: "Sputnik Грузия", url: "https://sputnik-georgia.ru/export/rss2/archive/index.xml", lang: "Russian" },
  { name: "Sputnik Азербайджан", url: "https://az.sputniknews.ru/export/rss2/archive/index.xml", lang: "Russian" },
  { name: "Sputnik Узбекистан", url: "https://uz.sputniknews.ru/export/rss2/archive/index.xml", lang: "Russian" },
  { name: "Sputnik Кыргызстан", url: "https://ru.sputnik.kg/export/rss2/archive/index.xml", lang: "Russian" },
  // More Russian-language outlets
  { name: "Новая газета", url: "https://novayagazeta.ru/feed/rss", lang: "Russian" },
  { name: "Вечерняя Москва", url: "https://vm.ru/rss", lang: "Russian" },
  { name: "Агентство городских новостей «Москва»", url: "https://www.mskagency.ru/rss/index.rss", lang: "Russian" },
  { name: "Военное обозрение", url: "https://topwar.ru/rss.xml", lang: "Russian" },
  { name: "Frank Media", url: "https://frankmedia.ru/feed", lang: "Russian" },
  { name: "Фонтанка.ру", url: "https://www.fontanka.ru/rss-feeds/rss.xml", lang: "Russian" },
  { name: "Бумага", url: "https://paperpaper.io/feed/", lang: "Russian" },
  { name: "Агентство", url: "https://www.agents.media/feed/", lang: "Russian" },
  { name: "Верстка", url: "https://verstka.media/feed", lang: "Russian" },
  { name: "7x7", url: "https://semnasem.org/rss/default.xml", lang: "Russian" },
  { name: "Сноб", url: "https://snob.ru/rss/", lang: "Russian" },
  { name: "Октагон", url: "https://octagon.media/rss.xml", lang: "Russian" },
  { name: "Readovka", url: "https://readovka.news/feed", lang: "Russian" },
  { name: "Корреспондент", url: "http://k.img.com.ua/rss/ru/all_news2.0.xml", lang: "Russian", home: "UA" },
  { name: "УНН", url: "https://www.unn.ua/rss/news_ru.xml", lang: "Russian", home: "UA" },
  { name: "Телеграф", url: "https://telegraf.com.ua/rss", lang: "Russian", home: "UA" },
  { name: "Хвиля", url: "https://hvylya.net/feed", lang: "Russian", home: "UA" },
  { name: "Inbusiness.kz", url: "https://inbusiness.kz/ru/rss", lang: "Russian", home: "KZ" },
  { name: "Ratel.kz", url: "https://ratel.kz/feed", lang: "Russian", home: "KZ" },
  { name: "Lada.kz", url: "https://www.lada.kz/rss.xml", lang: "Russian", home: "KZ" },
  { name: "Total.kz", url: "https://total.kz/ru/rss", lang: "Russian", home: "KZ" },
  { name: "Азия-Плюс", url: "https://asiaplustj.info/ru/rss", lang: "Russian" },
  { name: "Day.az", url: "https://news.day.az/rss/all.rss", lang: "Russian" },
  { name: "Haqqin.az", url: "https://haqqin.az/rss", lang: "Russian" },
  { name: "Новости-Грузия", url: "https://newsgeorgia.ge/feed/", lang: "Russian" },
  { name: "Point.md", url: "https://point.md/ru/rss", lang: "Russian" },
  { name: "Курсор", url: "https://cursorinfo.co.il/feed/", lang: "Russian", home: "IL" },
  { name: "BB.lv", url: "https://bb.lv/rss", lang: "Russian" },
  { name: "Sputnik Молдова", url: "https://md.sputniknews.ru/export/rss2/archive/index.xml", lang: "Russian" },

  // ---------- English ----------
  // Global and US
  { name: "BBC News", url: "https://feeds.bbci.co.uk/news/world/rss.xml", lang: "English" },
  { name: "The Guardian", url: "https://www.theguardian.com/world/rss", lang: "English" },
  { name: "The New York Times", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", lang: "English" },
  { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml", lang: "English" },
  { name: "Deutsche Welle", url: "https://rss.dw.com/rdf/rss-en-all", lang: "English" },
  { name: "France 24", url: "https://www.france24.com/en/rss", lang: "English" },
  { name: "Politico Europe", url: "https://www.politico.eu/feed/", lang: "English" },
  { name: "CNBC", url: "https://www.cnbc.com/id/100727362/device/rss/rss.html", lang: "English" },
  { name: "Bloomberg", url: "https://feeds.bloomberg.com/politics/news.rss", lang: "English" },
  { name: "The Washington Post", url: "https://feeds.washingtonpost.com/rss/world", lang: "English" },
  { name: "The Independent", url: "https://www.independent.co.uk/news/world/rss", lang: "English" },
  { name: "Euronews", url: "https://www.euronews.com/rss", lang: "English" },
  { name: "ABC News", url: "https://abcnews.go.com/abcnews/internationalheadlines", lang: "English" },
  { name: "CBS News", url: "https://www.cbsnews.com/latest/rss/world", lang: "English" },
  { name: "NPR", url: "https://feeds.npr.org/1004/rss.xml", lang: "English" },
  { name: "Financial Times", url: "https://www.ft.com/world?format=rss", lang: "English" },
  { name: "Fox News", url: "https://moxie.foxnews.com/google-publisher/world.xml", lang: "English" },
  { name: "NBC News", url: "https://feeds.nbcnews.com/nbcnews/public/world", lang: "English" },
  { name: "Los Angeles Times", url: "https://www.latimes.com/world-nation/rss2.0.xml", lang: "English" },
  { name: "MarketWatch", url: "https://feeds.content.dowjones.io/public/rss/mw_topstories", lang: "English" },
  { name: "Foreign Policy", url: "https://foreignpolicy.com/feed/", lang: "English" },
  { name: "Foreign Affairs", url: "https://www.foreignaffairs.com/rss.xml", lang: "English" },
  { name: "The Atlantic", url: "https://www.theatlantic.com/feed/channel/international/", lang: "English" },
  { name: "Time", url: "https://time.com/feed/", lang: "English" },
  { name: "The Hill", url: "https://thehill.com/news/feed/", lang: "English" },
  { name: "Axios", url: "https://api.axios.com/feed/", lang: "English" },
  { name: "Politico", url: "https://rss.politico.com/politics-news.xml", lang: "English" },
  { name: "PBS NewsHour", url: "https://www.pbs.org/newshour/feeds/rss/world", lang: "English" },
  { name: "Vox", url: "https://www.vox.com/rss/world-politics/index.xml", lang: "English" },
  { name: "HuffPost", url: "https://www.huffpost.com/section/world-news/feed", lang: "English" },
  { name: "The Christian Science Monitor", url: "https://rss.csmonitor.com/feeds/world", lang: "English" },
  { name: "The Intercept", url: "https://theintercept.com/feed/?rss", lang: "English" },
  { name: "National Review", url: "https://www.nationalreview.com/feed/", lang: "English" },
  { name: "Business Insider", url: "https://feeds.businessinsider.com/custom/all", lang: "English" },
  { name: "Fortune", url: "https://fortune.com/feed/", lang: "English" },
  { name: "Investing.com", url: "https://www.investing.com/rss/news.rss", lang: "English" },
  { name: "OilPrice.com", url: "https://oilprice.com/rss/main", lang: "English" },
  { name: "Rigzone", url: "https://www.rigzone.com/news/rss/rigzone_latest.aspx", lang: "English" },
  { name: "Semafor", url: "https://www.semafor.com/rss.xml", lang: "English" },
  { name: "UN News", url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml", lang: "English" },
  // Defence and security
  { name: "Defense News", url: "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml", lang: "English" },
  { name: "Breaking Defense", url: "https://breakingdefense.com/feed/", lang: "English" },
  { name: "Military Times", url: "https://www.militarytimes.com/arc/outboundfeeds/rss/?outputType=xml", lang: "English" },
  { name: "The War Zone", url: "https://www.twz.com/feed", lang: "English" },
  { name: "War on the Rocks", url: "https://warontherocks.com/feed/", lang: "English" },
  { name: "Defense One", url: "https://www.defenseone.com/rss/all/", lang: "English" },
  { name: "Responsible Statecraft", url: "https://responsiblestatecraft.org/feed/", lang: "English" },
  { name: "The National Interest", url: "https://nationalinterest.org/feed", lang: "English" },
  // Canada, UK, Ireland
  { name: "CBC News", url: "https://www.cbc.ca/webfeed/rss/rss-world", lang: "English" },
  { name: "Global News", url: "https://globalnews.ca/world/feed/", lang: "English" },
  { name: "The Globe and Mail", url: "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/world/", lang: "English" },
  { name: "National Post", url: "https://nationalpost.com/feed", lang: "English" },
  { name: "Sky News", url: "https://feeds.skynews.com/feeds/rss/world.xml", lang: "English", home: "GB" },
  { name: "New Statesman", url: "https://www.newstatesman.com/feed", lang: "English", home: "GB" },
  { name: "i News", url: "https://inews.co.uk/feed", lang: "English", home: "GB" },
  { name: "RTÉ", url: "https://www.rte.ie/feeds/rss/?index=/news/world/", lang: "English" },
  { name: "The Irish Times", url: "https://www.irishtimes.com/arc/outboundfeeds/feed-world/", lang: "English" },
  { name: "TheJournal.ie", url: "https://www.thejournal.ie/feed/", lang: "English" },
  // Europe
  { name: "Le Monde", url: "https://www.lemonde.fr/en/rss/une.xml", lang: "English", home: "FR" },
  { name: "RFI", url: "https://www.rfi.fr/en/rss", lang: "English", home: "FR" },
  { name: "The Local France", url: "https://www.thelocal.fr/feeds/rss.php", lang: "English", home: "FR" },
  { name: "Spiegel International", url: "https://www.spiegel.de/international/index.rss", lang: "English", home: "DE" },
  { name: "The Local Germany", url: "https://www.thelocal.de/feeds/rss.php", lang: "English", home: "DE" },
  { name: "Berlin Spectator", url: "https://berlinspectator.com/feed/", lang: "English", home: "DE" },
  { name: "The Local Sweden", url: "https://www.thelocal.se/feeds/rss.php", lang: "English" },
  { name: "Notes from Poland", url: "https://notesfrompoland.com/feed/", lang: "English", home: "PL" },
  { name: "LSM", url: "https://eng.lsm.lv/rss/", lang: "English" },
  { name: "Yle News", url: "https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS", lang: "English" },
  // Russia, Ukraine, Belarus, Caucasus, Central Asia
  { name: "The Moscow Times", url: "https://www.themoscowtimes.com/rss/news", lang: "English", home: "RU" },
  { name: "TASS English", url: "https://tass.com/rss/v2.xml", lang: "English", home: "RU" },
  { name: "RT", url: "https://www.rt.com/rss/news/", lang: "English", home: "RU" },
  { name: "Meduza English", url: "https://meduza.io/rss/en/all", lang: "English", home: "RU" },
  { name: "The Kyiv Independent", url: "https://kyivindependent.com/news-archive/rss/", lang: "English", home: "UA" },
  { name: "Ukrinform", url: "https://www.ukrinform.net/rss/block-lastnews", lang: "English", home: "UA" },
  { name: "Ukrainska Pravda", url: "https://www.pravda.com.ua/eng/rss/", lang: "English", home: "UA" },
  { name: "Kyiv Post", url: "https://www.kyivpost.com/feed", lang: "English", home: "UA" },
  { name: "Euromaidan Press", url: "https://euromaidanpress.com/feed/", lang: "English", home: "UA" },
  { name: "New Voice of Ukraine", url: "https://english.nv.ua/rss/all.xml", lang: "English", home: "UA" },
  { name: "Interfax-Ukraine", url: "https://en.interfax.com.ua/news/last.rss", lang: "English", home: "UA" },
  { name: "OC Media", url: "https://oc-media.org/feed/", lang: "English" },
  { name: "Civil Georgia", url: "https://civil.ge/feed", lang: "English" },
  { name: "The Times of Central Asia", url: "https://timesca.com/feed/", lang: "English" },
  { name: "Trend News Agency", url: "https://en.trend.az/feeds/index.rss", lang: "English" },
  { name: "News.am English", url: "https://news.am/eng/rss/", lang: "English" },
  { name: "Kazinform", url: "https://www.inform.kz/rss/eng.xml", lang: "English", home: "KZ" },
  { name: "The Astana Times", url: "https://astanatimes.com/feed/", lang: "English", home: "KZ" },
  { name: "Tengrinews English", url: "https://en.tengrinews.kz/news.rss", lang: "English", home: "KZ" },
  // Israel and the Middle East
  { name: "Haaretz", url: "https://www.haaretz.com/srv/haaretz-latest-headlines", lang: "English", home: "IL" },
  { name: "The Jerusalem Post", url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", lang: "English", home: "IL" },
  { name: "Ynetnews", url: "https://www.ynetnews.com/Integration/StoryRss3082.xml", lang: "English", home: "IL" },
  { name: "JNS", url: "https://www.jns.org/feed/", lang: "English", home: "IL" },
  { name: "Israel National News", url: "https://www.israelnationalnews.com/Rss.aspx", lang: "English", home: "IL" },
  { name: "Saudi Gazette", url: "https://saudigazette.com.sa/rssFeed/74", lang: "English", home: "SA" },
  { name: "Asharq Al-Awsat", url: "https://english.aawsat.com/feed", lang: "English", home: "SA" },
  { name: "Middle East Eye", url: "https://www.middleeasteye.net/rss", lang: "English" },
  { name: "Middle East Monitor", url: "https://www.middleeastmonitor.com/feed/", lang: "English" },
  { name: "The National", url: "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml", lang: "English" },
  { name: "Gulf News", url: "https://gulfnews.com/feed", lang: "English" },
  { name: "Khaleej Times", url: "https://www.khaleejtimes.com/stories.rss", lang: "English" },
  { name: "Al-Monitor", url: "https://www.al-monitor.com/rss", lang: "English" },
  // Iran
  { name: "Tehran Times", url: "https://www.tehrantimes.com/rss", lang: "English", home: "IR" },
  { name: "IRNA", url: "https://en.irna.ir/rss", lang: "English", home: "IR" },
  { name: "Mehr News", url: "https://en.mehrnews.com/rss", lang: "English", home: "IR" },
  { name: "Iran International", url: "https://www.iranintl.com/en/feed", lang: "English", home: "IR" },
  { name: "IranWire", url: "https://iranwire.com/en/feed/", lang: "English", home: "IR" },
  // Turkey
  { name: "Anadolu Agency", url: "https://www.aa.com.tr/en/rss/default?cat=world", lang: "English", home: "TR" },
  { name: "Daily Sabah", url: "https://www.dailysabah.com/rssFeed/10", lang: "English", home: "TR" },
  { name: "Turkish Minute", url: "https://www.turkishminute.com/feed/", lang: "English", home: "TR" },
  // Asia
  { name: "The Diplomat", url: "https://thediplomat.com/feed/", lang: "English" },
  { name: "Asia Times", url: "https://asiatimes.com/feed/", lang: "English" },
  { name: "CNA", url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6311", lang: "English" },
  { name: "The Straits Times", url: "https://www.straitstimes.com/news/world/rss.xml", lang: "English" },
  { name: "South China Morning Post", url: "https://www.scmp.com/rss/91/feed", lang: "English", home: "CN" },
  { name: "CGTN", url: "https://www.cgtn.com/subscribe/rss/section/world.xml", lang: "English", home: "CN" },
  { name: "Hong Kong Free Press", url: "https://hongkongfp.com/feed/", lang: "English", home: "CN" },
  { name: "Yonhap", url: "https://en.yna.co.kr/RSS/news.xml", lang: "English" },
  { name: "The Korea Times", url: "https://www.koreatimes.co.kr/www/rss/world.xml", lang: "English" },
  { name: "NK News", url: "https://www.nknews.org/feed/", lang: "English" },
  { name: "The Japan Times", url: "https://www.japantimes.co.jp/feed/", lang: "English", home: "JP" },
  { name: "Nippon.com", url: "https://www.nippon.com/en/feed/", lang: "English", home: "JP" },
  { name: "Japan Forward", url: "https://japan-forward.com/feed/", lang: "English", home: "JP" },
  // India and Pakistan
  { name: "The Times of India", url: "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms", lang: "English", home: "IN" },
  { name: "Hindustan Times", url: "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml", lang: "English", home: "IN" },
  { name: "The Hindu", url: "https://www.thehindu.com/news/international/feeder/default.rss", lang: "English", home: "IN" },
  { name: "NDTV", url: "https://feeds.feedburner.com/ndtvnews-world-news", lang: "English", home: "IN" },
  { name: "India Today", url: "https://www.indiatoday.in/rss/1206577", lang: "English", home: "IN" },
  { name: "The Economic Times", url: "https://economictimes.indiatimes.com/rssfeedstopstories.cms", lang: "English", home: "IN" },
  { name: "Mint", url: "https://www.livemint.com/rss/news", lang: "English", home: "IN" },
  { name: "Business Standard", url: "https://www.business-standard.com/rss/latest.rss", lang: "English", home: "IN" },
  { name: "Dawn", url: "https://www.dawn.com/feeds/home", lang: "English" },
  { name: "The Express Tribune", url: "https://tribune.com.pk/feed/home", lang: "English" },
  // Australia and New Zealand
  { name: "ABC Australia", url: "https://www.abc.net.au/news/feed/2942460/rss.xml", lang: "English" },
  { name: "The Sydney Morning Herald", url: "https://www.smh.com.au/rss/world.xml", lang: "English" },
  { name: "The Conversation", url: "https://theconversation.com/global/articles.atom", lang: "English" },
  // Africa
  { name: "Hespress English", url: "https://en.hespress.com/feed", lang: "English", home: "MA" },
  { name: "North Africa Post", url: "https://northafricapost.com/feed", lang: "English", home: "MA" },
  { name: "Africanews", url: "https://www.africanews.com/feed/rss", lang: "English" },
  { name: "The Africa Report", url: "https://www.theafricareport.com/feed/", lang: "English" },
  { name: "Egypt Independent", url: "https://www.egyptindependent.com/feed/", lang: "English" },
  // Latin America
  { name: "The Rio Times", url: "https://www.riotimesonline.com/feed/", lang: "English", home: "BR" },
  { name: "MercoPress", url: "https://en.mercopress.com/rss", lang: "English" },
  { name: "Agência Brasil", url: "https://agenciabrasil.ebc.com.br/en/rss/ultimasnoticias/feed.xml", lang: "English", home: "BR" },
  { name: "Brazil Reports", url: "https://brazilreports.com/feed/", lang: "English", home: "BR" },
  { name: "Buenos Aires Times", url: "https://www.batimes.com.ar/feed", lang: "English" },
  // More English-language outlets
  { name: "Modern Diplomacy", url: "https://moderndiplomacy.eu/feed/", lang: "English" },
  { name: "Geopolitical Monitor", url: "https://www.geopoliticalmonitor.com/feed/", lang: "English" },
  { name: "Global Voices", url: "https://globalvoices.org/feed/", lang: "English" },
  { name: "IPS News", url: "https://www.ipsnews.net/feed/", lang: "English" },
  { name: "Rest of World", url: "https://restofworld.org/feed/latest/", lang: "English" },
  { name: "Project Syndicate", url: "https://www.project-syndicate.org/rss", lang: "English" },
  { name: "Atlantic Council", url: "https://www.atlanticcouncil.org/feed/", lang: "English" },
  { name: "Jamestown Foundation", url: "https://jamestown.org/feed/", lang: "English" },
  { name: "The New Republic", url: "https://newrepublic.com/rss.xml", lang: "English" },
  { name: "The Nation", url: "https://www.thenation.com/feed/?post_type=article", lang: "English" },
  { name: "Mother Jones", url: "https://www.motherjones.com/feed/", lang: "English" },
  { name: "Reason", url: "https://reason.com/feed/", lang: "English" },
  { name: "The American Conservative", url: "https://www.theamericanconservative.com/feed/", lang: "English" },
  { name: "The Daily Signal", url: "https://www.dailysignal.com/feed/", lang: "English" },
  { name: "Washington Free Beacon", url: "https://freebeacon.com/feed/", lang: "English" },
  { name: "Roll Call", url: "https://rollcall.com/feed/", lang: "English" },
  { name: "Fox Business", url: "https://moxie.foxbusiness.com/google-publisher/latest.xml", lang: "English" },
  { name: "Financial Post", url: "https://financialpost.com/feed", lang: "English" },
  { name: "FXStreet", url: "https://www.fxstreet.com/rss/news", lang: "English" },
  { name: "Task & Purpose", url: "https://taskandpurpose.com/feed/", lang: "English" },
  { name: "Air & Space Forces Magazine", url: "https://www.airandspaceforces.com/feed/", lang: "English" },
  { name: "Naval News", url: "https://www.navalnews.com/feed/", lang: "English" },
  { name: "USNI News", url: "https://news.usni.org/feed", lang: "English" },
  { name: "bne IntelliNews", url: "https://www.intellinews.com/feed/", lang: "English" },
  { name: "Emerging Europe", url: "https://emerging-europe.com/feed/", lang: "English" },
  { name: "Brussels Signal", url: "https://brusselssignal.eu/feed/", lang: "English" },
  { name: "Remix News", url: "https://rmx.news/feed/", lang: "English" },
  { name: "Morning Star", url: "https://morningstaronline.co.uk/rss.xml", lang: "English", home: "GB" },
  { name: "Byline Times", url: "https://bylinetimes.com/feed/", lang: "English", home: "GB" },
  { name: "UnHerd", url: "https://unherd.com/feed/", lang: "English", home: "GB" },
  { name: "LabourList", url: "https://labourlist.org/feed/", lang: "English", home: "GB" },
  { name: "ConservativeHome", url: "https://conservativehome.com/feed/", lang: "English", home: "GB" },
  { name: "Left Foot Forward", url: "https://leftfootforward.org/feed/", lang: "English", home: "GB" },
  { name: "Jewish Insider", url: "https://jewishinsider.com/feed/", lang: "English", home: "IL" },
  { name: "The Forward", url: "https://forward.com/feed/", lang: "English", home: "IL" },
  { name: "JTA", url: "https://www.jta.org/feed", lang: "English", home: "IL" },
  { name: "The Algemeiner", url: "https://www.algemeiner.com/feed/", lang: "English", home: "IL" },
  { name: "Globes", url: "https://en.globes.co.il/WebService/Rss/RssFeeder.asmx/FeederNode?iID=942", lang: "English", home: "IL" },
  { name: "Mondoweiss", url: "https://mondoweiss.net/feed/", lang: "English", home: "IL" },
  { name: "Enab Baladi", url: "https://english.enabbaladi.net/feed/", lang: "English" },
  { name: "The Syrian Observer", url: "https://syrianobserver.com/feed", lang: "English" },
  { name: "Amwaj.media", url: "https://amwaj.media/rss", lang: "English" },
  { name: "Kayhan Life", url: "https://kayhanlife.com/feed/", lang: "English", home: "IR" },
  { name: "ISNA", url: "https://en.isna.ir/rss", lang: "English", home: "IR" },
  { name: "Nordic Monitor", url: "https://nordicmonitor.com/feed/", lang: "English", home: "TR" },
  { name: "Stockholm Center for Freedom", url: "https://stockholmcf.org/feed/", lang: "English", home: "TR" },
  { name: "OpIndia", url: "https://www.opindia.com/feed/", lang: "English", home: "IN" },
  { name: "Organiser", url: "https://organiser.org/feed/", lang: "English", home: "IN" },
  { name: "Zee News", url: "https://zeenews.india.com/rss/world-news.xml", lang: "English", home: "IN" },
  { name: "Hindu BusinessLine", url: "https://www.thehindubusinessline.com/feeder/default.rss", lang: "English", home: "IN" },
  { name: "Frontline", url: "https://frontline.thehindu.com/feeder/default.rss", lang: "English", home: "IN" },
  { name: "Geo News", url: "https://www.geo.tv/rss/1/1", lang: "English" },
  { name: "ARY News", url: "https://arynews.tv/feed/", lang: "English" },
  { name: "Business Recorder", url: "https://www.brecorder.com/feeds/latest-news", lang: "English" },
  { name: "RTHK", url: "https://rthk9.rthk.hk/rthk/news/rss/e_expressnews_elocal.xml", lang: "English", home: "CN" },
  { name: "Yabiladi", url: "https://en.yabiladi.com/rss/news.xml", lang: "English", home: "MA" }
];
